# proudly/partly taken from https://linuxhandbook.com/nginx-reverse-proxy-docker/ and adapted

version: "3.7"

services:
    nginx_reverse_proxy:
        image: nginxproxy/nginx-proxy:latest
        pull_policy: always
        container_name: nginx_reverse_proxy
        volumes:
            - config:/etc/nginx/conf.d
            - html:/usr/share/nginx/html
            - dhparam:/etc/nginx/dhparam
            - vhost:/etc/nginx/vhost.d
            - certs:/etc/nginx/certs
            - /run/docker.sock:/tmp/docker.sock:ro
        networks: 
            - net
        ports:
            - 80:80
            - 443:443
        restart: always

    letsencrypt:
        image: nginxproxy/acme-companion:latest
        pull_policy: always
        container_name: letsencrypt_helper
        volumes:
            - html:/usr/share/nginx/html
            - dhparam:/etc/nginx/dhparam
            - vhost:/etc/nginx/vhost.d
            - certs:/etc/nginx/certs
            - /run/docker.sock:/var/run/docker.sock:ro
        networks: 
            - net
        environment:
            NGINX_PROXY_CONTAINER: nginx_reverse_proxy
            DEFAULT_EMAIL: ${LETSENCRYPT_EMAIL:?You need to specify a mail for letsencrypt}
        restart: always
        depends_on:
            - nginx_reverse_proxy
    
    portainer:
        image: portainer/portainer-ce:latest
        pull_policy: always
        container_name: portainer
        volumes:
            - data_portainer:/data
            - /var/run/docker.sock:/var/run/docker.sock
        networks: 
            - net
        environment:
            VIRTUAL_HOST: ${PORTAINER_URL:?You need to specify on which URL you want your portainer webinterface}
            LETSENCRYPT_HOST: ${PORTAINER_URL:?You need to specify on which URL you want your portainer webinterface}
            VIRTUAL_PORT: 9000
        restart: always
        depends_on:
            - nginx_reverse_proxy
            - letsencrypt
            
volumes:
    config:
    certs:
    html:
    vhost:
    dhparam:
    data_portainer:

networks:
    net:
        external: true